eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-3-109-155-3.ap-south-1.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: localhost
